### ISSUE TITLE
Quoted strings include the quotes

### ISSUE THREAD

**Issue by delkano** [taufik-nurrohman/y-a-m-l#2]
Using from_yaml to decode something like
`test: 'This is a quoted string'`
will return a PHP string containing the quotes: `"test" => "'This is a quoted string'"`

Since to_yaml correctly quotes strings that contain special characters, like quotes, a few cycles of load and save (from_yaml then to_yaml) can create monstrosities like `test: ''''''This is a quoted string''''''`.

**Comment by taufik-nurrohman** [comment]
Probably a bug. The correct behaviour is to unwrap the single quote.

**Comment by taufik-nurrohman** [comment]
It happens only if the line contains `": "` sequence (Example: `"test: 'This is: a quoted string'"`). So `"test: 'This is a quoted string'"` should give you correct result even before the recent commits.
